language: python
sudo: false
python:
  - "2.7"
  - "3.3"
  - "3.4"
install:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  # Create the environment.
  - conda create -q -n testenv python=$TRAVIS_PYTHON_VERSION
  - source activate testenv
  # NOTE: cython is only temporarily needed for building KK2.
  # Once we have KK2 binary builds on binstar we can remove this dependency.
  - conda install pip numpy matplotlib scipy h5py pyqt pyzmq ipython requests pytest pip flake8 coverage cython
  - pip install klustakwik2
  - pip install six vispy coveralls responses python-coveralls pytest-cov
before_script:
    - export DISPLAY=:99.0
    - /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1400x900x24 -ac +extension GLX +render
script:
  - make test
after_success:
  - coveralls
