name: phy
dependencies:
  - python
  - numpy
  - matplotlib
  - scipy
  - h5py
  - pyqt
  - pip:
    - pyopengl
    - vispy
    - requests
    - traitlets
    - tqdm
    - six
    - joblib
    - click
