site_name: phy
pages:
- Getting started:
  - Introduction: 'index.md'
  - Release notes: 'release.md'
  - Installation: 'installation.md'
- Interactive visualization: 'visualization.md'
- Manual clustering: 'clustering.md'
- Customization: 'customization.md'
- Keyboard shortcuts and snippets: 'shortcuts.md'
- Developing with phy: 'developer.md'
theme: readthedocs
